### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by mg-1999** [exteso/Alf.ioBackoffice#2]
When I try to sign in on a newly created user it won't let me. It just goes back for the blank front-page. I use the option with the qr scanner.

**Comment by cbellone** [comment]
Did you create the user on your local system? If yes:

- are you generating the QR-Code from your public IP address (either LAN or
WAN)? E.g. what's the address on the location bar of the browser?
http://localhost... or http://192.168.x.x?
- is the address accessible from the phone? E.g. are they on the same
network? Did you try to open the website with the phone's browser?

Could you please share the QR-Code image with me? If yes, I will contact
you privately in order to have it.

In any case, we should improve the error notifications stating what's
happened... this will be fixed in the next releases.

Thank you very much for your help!

Celestino


2016-01-29 23:58 GMT+01:00 Matthijs <notifications@github.com>:

**Comment by mg-1999** [comment]
I forgot to update my local version to 1.7 so that would be the the problem.

Op zo 31 jan. 2016 17:30 schreef Celestino Bellone <notifications@github.com
>:

> Closed #2 <https://github.com/exteso/Alf.ioBackoffice/issues/2> via
> 8d8f571
> <https://github.com/exteso/Alf.ioBackoffice/commit/8d8f5711ea72dae65b6c04b1ab51dd9378233385>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exteso/Alf.ioBackoffice/issues/2#event-533151500>.
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg
